// Purpose: Detect holdout leakage, biased selection, invalid plugins and budget overruns.
import test from 'node:test';
import assert from 'node:assert/strict';
import { experiment, toPack } from '../src/index.mjs';
const candidate = id => ({ id, instructions: 'classify', criteria: { yes: 'yes', no: 'no' } });
const spec = () => ({ candidates: [candidate('first'), candidate('second')], development: [{ id: 'd', text: 'development', label: 'yes' }], heldout: [{ id: 'h', text: 'heldout', label: 'no' }], maxEvaluations: 10 });
test('holdout scores cannot choose the winner and labels never reach predictor', async () => { const seen = []; const r = await experiment(spec(), { predictor: async (c, row) => { assert.deepEqual(Object.keys(row).sort(), ['id', 'text']); seen.push([c.id, row.id]); return { label: c.id === 'first' ? 'yes' : 'no' }; } }); assert.equal(r.selectedCandidate.id, 'first'); assert.equal(r.heldout.accuracy, 0); assert.deepEqual(seen, [['first', 'd'], ['second', 'd'], ['first', 'h']]); assert.equal(r.calls, 3); });
test('stable input order breaks development ties', async () => { const r = await experiment(spec(), { predictor: async () => ({ label: 'yes' }) }); assert.equal(r.selectedCandidate.id, 'first'); assert.equal(toPack(r.selectedCandidate).model, 'jev-1.13.0'); });
test('budget fails before any request rather than partially comparing candidates', async () => { let calls = 0; await assert.rejects(experiment({ ...spec(), maxEvaluations: 2 }, { predictor: async () => { calls++; return { label: 'yes' }; } }), /budget/); assert.equal(calls, 0); });
test('reject cross-split duplicate text and unknown labels', async () => { const s = spec(); s.heldout[0].text = 'development'; await assert.rejects(experiment(s, { predictor: async () => ({ label: 'yes' }) }), /unique/); await assert.rejects(experiment(spec(), { predictor: async () => ({ label: 'invalid' }) }), /unknown label/); });
test('proposer receives development only and output enters a later round', async () => { let calls = 0; const r = await experiment({ ...spec(), rounds: 1 }, { predictor: async c => ({ label: c.id === 'improved' ? 'yes' : 'no' }), proposer: async context => { calls++; assert.ok(!('heldout' in context)); assert.ok(!JSON.stringify(context).includes('heldout')); return [candidate('improved')]; } }); assert.equal(calls, 1); assert.equal(r.selectedCandidate.id, 'improved'); assert.equal(r.calls, 4); });
test('mutating predictor cannot alter candidate provenance', async () => { const s = spec(); const r = await experiment(s, { predictor: async c => { c.instructions = 'mutated'; return { label: 'yes' }; } }); assert.equal(r.selectedCandidate.instructions, 'classify'); assert.equal(s.candidates[0].instructions, 'classify'); });
test('invalid candidate sets and hanging predictor fail explicitly', async () => { const s = spec(); s.candidates[1].criteria = { other: 'other', no: 'no' }; await assert.rejects(experiment(s, { predictor: async () => ({ label: 'no' }) }), /label sets/); await assert.rejects(experiment(spec(), { predictor: () => new Promise(() => {}), timeoutMs: 5 }), /deadline/); });
